import './globals.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header>
          <nav>
            <ul className="flex justify-around p-5 border-b-2 uppercase">
              <li><Link className='hover:underline' href={`/`}>Home</Link></li>
              <li><Link className='hover:underline' href={`/blog`}>Blog</Link></li>
              <li><Link className='hover:underline' href={`/contact`}>Contact</Link></li>
              <li><Link className='font-bold uppercase' href={`/`}>Swanky</Link></li>
              <li><Link className='hover:underline' href={`/contact`}>Contact</Link></li>
              <li><Link className='hover:underline' href={`/blog`}>Blog</Link></li>
              <li><Link className='hover:underline' href={`/`}>Home</Link></li>
            </ul>
          </nav>
        </header>
        {children}
      <footer className='border-t-2 flex justify-around leading-8 py-[5rem]'>
        <div>
          <h1 className='font-bold uppercase text-2xl'>Swanky</h1>
          <p className='w-[20rem] text-slate-400'>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae error harum, quis officiis consequuntur beatae fugiat rerum libero quia cum?</p>
          <p className='text-slate-300 border-b-2'>Enter Your Email Adress...</p>
        </div>
        <div className='font-bold'>
          <h1 className='text-2xl '>Quick Links</h1>
          <p className='uppercase hover:underline'>Home</p>
          <p className='uppercase hover:underline'>About</p>
          <p className='uppercase hover:underline'>Shop</p>
          <p className='uppercase hover:underline'>Blogs</p>
          <p className='uppercase hover:underline'>Contact</p>
        </div>
        <div className='font-bold'>
          <h1 className='text-2xl '>Help & Info</h1>
          <p className='uppercase hover:underline'>Track your order</p>
          <p className='uppercase hover:underline'>Returns policies</p>
          <p className='uppercase hover:underline'>Shipping + delivery</p>
          <p className='uppercase hover:underline'>Contact us</p>
          <p className='uppercase hover:underline'>Faqs</p>
        </div>
        <div>
          <h1 className='text-2xl font-bold'>Contact Us</h1>
          <p className='text-slate-400'>Do you have any queries or suggestions?</p>
          <p className='font-bold underline'>youinfo@gmail.com</p>
          <p className='text-slate-400'>If you need support? Just give us a call.</p>
          <p className='font-bold underline'>+55 111 222 333 44</p>
        </div>
      </footer>
      </body>
    </html>
  )
}
