import './globals.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <header>
          <nav>
            <ul className="flex justify-around p-5 border-b-2">
              <li><Link href={`/`}>Home</Link></li>
              <li><Link href={`/blog`}>Blog</Link></li>
              <li><Link href={`/contact`}>Contact</Link></li>
              <li><Link href={`/`} className="font-bold uppercase">Swanky</Link></li>
              <li><Link href={`/contact`}>Contact</Link></li>
              <li><Link href={`/Blog`}>Blog</Link></li>
              <li><Link href={`/`}>Home</Link></li>

            </ul>
          </nav>
        </header>
        {children}
      <footer className='border-t-2'>
        <h1>Here is footer</h1>
        <section>
          <h1>Swanky</h1>
          <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Repudiandae error harum, quis officiis consequuntur beatae fugiat rerum libero quia cum?</p>
          <p className='text-grey border-b-2'>Enter Your Email Adress...</p>
        </section>
      </footer>
      </body>
    </html>
  )
}
